### PR TITLE
Feat: Add button to expand bottomsheet

### PR DESCRIPTION
**Pull request by darkvoid32**
Removed extra `ExperimentalMaterialApi`.

Added button to expand bottomSheetScaffold since dragging up might clash with device android device functions.

WhatsApp Image 2022-07-16 at 8 19 02 PM

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Hey! That's an awesome idea. I tried to play around with a button myself when I first added the bottom sheet, and I do think it's the better way to do it (I just got lazy and couldn't find a good place to put it.

Do you mind adding a screenshot of your change?

**Comment by darkvoid32** [comment]
Updated with screenshot!

**Comment by thunderbiscuit** [comment]
ACK [a68aed4](https://github.com/thunderbiscuit/devkit-wallet/pull/31/commits/a68aed4e6c94d5b90e418a3e2466aa9f8f29aeee).

**Review by thunderbiscuit — APPROVED** [review]
Good to go!

**Pull request merged**
