### PR TITLE
Remove outdated QRGenearator library 

### PR DESCRIPTION
**Pull request by caiofaustino**
And add own simple QRCodeGenerator class.

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Ok that's great! I've been meaning to deal with this old library for a while but couldn't really find good examples on how to do without it.

My only concern is I've never implemented a QR building algo like that (as simple as it looks), and in this case it's of the utmost importance that it always transmits the right data (the bitcoin address). I don't have a strong sense of how to judge whether it's watertight or not (not that I really looked at the source code for the old library you might say haha but still; I should hold myself to higher standards). 

How would you suggest I make sure this is a good replacement? Is the code taken from another implementation I can take a look at, or should we maybe add some tests with corner cases?

Thanks for taking the time to make the app better. I do want to get this merged, I just want to make sure I don't merge blindly before doing due diligence.

**Comment by caiofaustino** [comment]
Yeah I totally agree. I don't have much experience with this either.

>not that I really looked at the source code for the old library you might say haha but still; I should hold myself to higher standards)
It's precisely this 😅 I just went looking for what that outdated lib was doing.
https://github.com/androidmads/QRGenerator/blob/master/QRGenearator/src/main/java/androidmads/library/qrgenearator/QRGEncoder.java#L205

My understanding is that the important part is really done inside ZXing. That's what actually encodes the data and transforms it into the barcodes. Then ` androidmads` was just taking the `BitMatrix` and turning it into a Bitmap.
And instead of using the generic `MultiFormatWriter` I thought it would be easier to just use the `QRCodeWriter` directly.

**Comment by caiofaustino** [comment]
But tbh the only test I did was to generate a new address, read it in a normal QR code scanning app, and match the result with the address String. And it seemed to work fine. But if you have a Testnet wallet to try to make a transaction that would be better, I still need to set that up on my end.

**Comment by thunderbiscuit** [comment]
Hey just want to say I'm stuck on other things at the moment but my schedule should clear up second week of Feb! I didn't forget about this.

**Comment by thunderbiscuit** [comment]
Hey @caiofaustino I just want to say I'm stuck on other things at the moment but my schedule should clear up second week of Feb! I didn't forget about this.

**Comment by caiofaustino** [comment]
No worries, I did have much time to do check out more of the project yet either.

**Comment by thunderbiscuit** [comment]
Hey @caiofaustino! After looking into this for a little bit, I realized you were right and the encoding itself is handled by the `xzing` library. The only thing they don't do is transform that `BitMatrix` to a `BitMap`, which is what I needed to display. 

In any case I found a good fix for it that only needed 6 lines changed, so I used that instead of this particular PR, but it looks very much like your code. It's basically just building that BitMap with dark and light pixels. Thanks for helping me dig into this, and finally get rid of my JCenter dependency!

I'm glad to see interest for the bitcoindevkit on mobile. Feel free to contribute more if you are interested!

**Comment by caiofaustino** [comment]
Sure man, no problem.

**Pull request closed without merging**
